### ISSUE TITLE
Need Only Magento  ?

### ISSUE THREAD

**Issue by serkandyck** [guohuadeng/magento-app-v2#1]
hello, i just tested this source but content not load. and this connect only magento rest api ? or any plugin for this ?

**Comment by wenzhixin** [comment]
You can run this app use `ionic run ios` or `ionic run android`.

**Comment by serkandyck** [comment]
yep i can build this app but not connecting kiku and not load data

**Comment by wenzhixin** [comment]
Magento need to support the API of the app.

**Comment by guohuadeng** [comment]
# change /www/js/config.js

# var isRealease = 0;

# or 

# var isRealease = 1;
