### ISSUE TITLE
百度地图，取当前位置仍然会取不到。看默认变成广州

### ISSUE THREAD

**Issue by guohuadeng** [guohuadeng/magento-app-v2#33]
附近商家中，位置默认调整为广州。
点击按键获取位置时，获取经纬度并将相关地名自动录入 “位置”那个框
看是否可如上实现，不成就获取位置后，在“位置”处显示当前位置。

**Comment by guohuadeng** [comment]
另外，附近商家处，输入位置后，经常要点击两次，才能搜索附近商家

**Comment by guohuadeng** [comment]
bug?
点击地图模式后，点击列表模式，再点击地图模式，地图会只出现一个小角。
这个是否ionic的tabs的bug，如果是，最好调整为普通div层

**Comment by guohuadeng** [comment]
已改为默认广州。
列表页中无法滚动，比如查距离 广州 ，2000公里，出来的更多内容无法滚动显示

**Comment by guohuadeng** [comment]
列表页加一个ion-scroll可以滚动了

**Comment by wenzhixin** [comment]
地图的bug已经解决
