### ISSUE TITLE
地图大头钉功能，要在大头钉上方加上店名，半径默认用搜索时设置的半径（如200），加上中心位置用蓝色大头钉

### ISSUE THREAD

**Issue by guohuadeng** [guohuadeng/magento-app-v2#34]
举例：如果当前位置输入广州，是要把得到的“广州”座标位置变蓝色，并在上方标注“广州”。
搜索到的商业家就用红色钉，上方显示名称。
半径就用在距离（公里）那里输入的数值，如200公里
百度的zoom算法不太清楚，可将中国视为 3000公里x3000公里的方形。
如输入的是200，则默认可显示以广州为中心的横屏长度为200公里x2=400公里的范围

**Comment by guohuadeng** [comment]
已经设置好zoom的比例

**Comment by wenzhixin** [comment]
增加名称

**Comment by wenzhixin** [comment]
用自定义 icon 代替
