### ISSUE TITLE
todo:高级查询页面增加属性二级联动功能

### ISSUE THREAD

**Issue by guohuadeng** [guohuadeng/magento-app-v2#37]
高级查询页面
暂时是实现 形状属性 和 规格属性方面的联动
形状有：长方形，圆形，正方形，椭圆形，三角形
规格有多种，如：(长方形)12x6毫米，(长方形)15*8毫米，(圆形)直径12毫米，等

规格的 ()中是其对应的形状，看在前端实现选择长方形时，规格列表中只出现前缀为(长方形)的规格，选择(圆形)等其它时也类似，选择全部就全部出现。
后台的属性管理没有联动功能，此功能也可以考虑在json接口中实现。

**Comment by wenzhixin** [comment]
已在前端做处理

**Comment by guohuadeng** [comment]
选长方形时正常，选其它形状时，规格的下拉内容不正常会紧缩

**Comment by guohuadeng** [comment]
举例，形状先选长方形，规格选个相关的 长方形12x6，然后形状再选正方形，则规格的下拉框会出错，无东西显示，其值是一个不正确的值，这个时候post搜索，将什么也搜索不到。
应该是 dom内容的变更，没有及时反应到ng-model内容，搜索下，一般要用 angularjs的directive来实现。或者我们全部用ng-model来实现，将"全部"也绑定到某个 {{}}的值里。
