### ISSUE TITLE
Great Share

### ISSUE THREAD

**Issue by chrigui** [guohuadeng/magento-app-v2#43]
Let me know if you do freelancing please i want to translate it and add my payment gateway to the app please.
my email is tarik At chrigui.com

**Comment by peterfiasco** [comment]
@chrigui Please does this app work with configurable products?

Thanks

**Comment by chrigui** [comment]
Have no idea I forked it from @guohuadeng

**Comment by peterfiasco** [comment]
@chrigui Please how did you get it to work with your magento store. Please if you can be detailed I will appreciate it.

**Comment by peterfiasco** [comment]
@guohuadeng Please kindly provide documentation on how to use your app

**Comment by peterfiasco** [comment]
@chrigui I have a different magento app but I am stuck with getting it to work with product options, are you an ionic developer. I could share the files with you

**Comment by chrigui** [comment]
I failed to make it work please check with the app developer

**Comment by chrigui** [comment]
Sure my email is tarik@chrigui.com I'll have a look

**Comment by guohuadeng** [comment]
Thanks all.
We can do free freelancing. But so busy for our new app.
this is a multilingual version.
and we support paypal/wechat pay method.

**Comment by peterfiasco** [comment]
Good day,

I have a magento site. I know a bit about ionic customization. How do I get
my site to work with your app?

Thanks
